server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;

        # A mágica acontece aqui!
        # Tenta achar o arquivo. Se não achar, tenta a pasta. Se não achar, devolve o index.html
        try_files $uri $uri/ /index.html;
    }

    # Páginas de erro padrão
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}