spring.application.name=backend


spring.datasource.url=jdbc:postgresql://localhost:5432/escuta_if
spring.datasource.username=postgres
spring.datasource.password=adm

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=seu_usuario_do_mailtrap
#spring.mail.password=sua_senha_do_mailtrap
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=seu_segredo_para_jwt;